---
- name: Install Docker on remote host
  hosts: remote-docker-node
  become: true

  tasks:
    - name: Update apt package manager cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present
      become: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
      become: true

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
      become: true

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true
    - name: Pull Docker image
      docker_image:
        name: ryanlee0517/mypythonapp
        source: pull

    - name: Run Docker container
      docker_container:
        name: my-container
        image: ryanlee0517/mypythonapp
        state: started
        restart_policy: always
        ports:
          - "80:8080"